- composer.json
- extension.neon
- src/Type/Symfony/SerializerInterfaceDynamicReturnTypeExtension.php
- tests/Symfony/NeonTest.php
- tests/Type/Symfony/SerializerInterfaceDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/serializer.php
The return type of deserialize depends on the type you ask it for, so this gets us the correct type.
> Add support for Serializer::deserialize

- phpstan.neon
- src/Rules/Symfony/ContainerInterfacePrivateServiceRule.php
- tests/Rules/Symfony/ContainerInterfacePrivateServiceRuleTest.php
- tests/Rules/Symfony/ExampleLegacyServiceSubscriber.php
- tests/Rules/Symfony/ExampleLegacyServiceSubscriberFromAbstractController.php
- tests/Rules/Symfony/ExampleLegacyServiceSubscriberFromLegacyController.php
- tests/Rules/Symfony/ExampleServiceSubscriberFromAbstractController.php
- tests/Rules/Symfony/ExampleServiceSubscriberFromLegacyController.php
In Symfony 4.2 the ServiceSubscriberInterface has been moved into its own contracts namespace. This commit adds support for the new interface and adds more test-coverage for all possible cases/combinations.
This is a follow-up on #19 (https://github.com/phpstan/phpstan-symfony/commit/c340de842c656bdf5ea01eed07fce58ceb6eeb61)
> Honor new contracts namespace as-of Symfony 4.2 for ServiceSubscriberInterface

- src/Type/Symfony/SerializerInterfaceDynamicReturnTypeExtension.php
- tests/Type/Symfony/SerializerInterfaceDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/serializer.php
As correctly pointed out by @jvasseur, it's possible to have arrays of arrays.
https://github.com/phpstan/phpstan-symfony/pull/34#discussion_r256559742
Of course really we should check what normalizers are in the container, and only if ArrayNormalizer is active support this, and possibly be able to say what objects are deserializable,
> Add support for recursive types to Serializer

- src/Symfony/XmlServiceMapFactory.php
- tests/Symfony/ServiceMapTest.php
- tests/Symfony/containers/bugfix%2Fcontainer.xml
When the URI of the container contains escaped characters like `%2F`, `simplexml_load_file` throw an error.
~According [to the documentation](http://php.net/manual/en/function.simplexml-load-file.php) :~
> ~Libxml 2 unescapes the URI, so if you want to pass e.g. b&c as the URI parameter a, you have to call simplexml_load_file(rawurlencode('http://example.com/?a=' . urlencode('b&c'))). Since PHP 5.1.0 you don't need to do this because PHP will do it for you.~
~I don't understand exactly what should not be done since PHP 5.1.0, but with PHP 7.2, I reproduced the following error :~
```php
$jd = 'jdjd/test.xml';
$jdSlash = rawurlencode('jdjd/test.xml');
$jnSlash = rawurlencode('jn%2Fjn/test.xml');
$jn = 'jn%2Fjn/test.xml';
var_dump($jd); // string(13) "jdjd/test.xml" …
```
> Fix issue while loading a container

- composer.json
- extension.neon
- src/Type/Symfony/EnvelopeReturnTypeExtension.php
- tests/Symfony/NeonTest.php
- tests/Type/Symfony/EnvelopeReturnTypeExtensionTest.php
- tests/Type/Symfony/ExtensionTestCase.php
- tests/Type/Symfony/envelope_all.php
> Add EnvelopeReturnTypeExtension for symfony/messenger

- README.md
- composer.json
- extension.neon
- rules.neon
Doing this because issue of false positives in test cases, https://github.com/phpstan/phpstan-symfony/issues/27, but anyway, its the style in all the other phpstan plugins, so would be good to do the same here
> Separate rules from extension as in other phpstan extensions

- README.md
Added correct `container_xml_path` for Symfony 5
> `container_xml_path` for Symfony 5

- extension.neon
- stubs/FormBuilderInterface.php
- stubs/FormInterface.php
- stubs/HeaderBag.php
- stubs/Session.php
These are types where PHPStan on lvl 6 was complaining about missing iterable information (in our codebase) - there will be probably more, but I think especially the form ones are quite wide spread.
Original types for reference:
* [FormBuilderInterface](https://github.com/symfony/symfony/blob/v5.0.1/src/Symfony/Component/Form/FormBuilderInterface.php)
* [FormInterface](https://github.com/symfony/symfony/blob/v5.0.1/src/Symfony/Component/Form/FormInterface.php)
* [Session](https://github.com/symfony/symfony/blob/v5.0.1/src/Symfony/Component/HttpFoundation/Session/Session.php)
* [HeaderBag](https://github.com/symfony/symfony/blob/v5.0.1/src/Symfony/Component/HttpFoundation/HeaderBag.php)
As per discussion with @ondrejmirtes I am not adding any dependencies.
> Add stubs for (some) Symfony iterable types

- README.md
> README: fix spacing

- extension.neon
- stubs/ChoiceLoaderInterface.stub
- stubs/Constraint.stub
- stubs/ContainerBuilder.stub
- stubs/EventSubscriberInterface.stub
- stubs/ExtensionInterface.stub
- stubs/FormTypeInterface.stub
- stubs/FormView.stub
Mostly adding `array<mixed>` where symfony documents `array` (phpstan will complain about this on max level when implementing these interfaces). 
Also added an "empty" `ContainerBuilder` stub, since phpstan complained about not knowing the class when seeing it in `ExtensionInterface.stub`. If there's another way to fix this please let me know.
These changes are based off of symfony 4.4 and tested on a medium to large-ish codebase.
> Add a bunch of stubs

- src/Type/Symfony/InputInterfaceGetOptionDynamicReturnTypeExtension.php
- tests/Type/Symfony/InputInterfaceGetOptionDynamicReturnTypeExtensionTest.php
I read discussion in #45 about adding `int` type for `getOption`. But reading Symfony source code and doing some tests, `int` type is only possible if an `int` default value has been passed to `addOption`.
> Adjusts getOption return type if no default value.

- composer.json
This removes the deprecations. These are confusing for contributors.
> Bump minimum versions to prevent deprecations while running in lowest mode

- extension.neon
- stubs/FormTypeExtensionInterface.stub
- stubs/FormTypeInterface.stub
Since it implements nearly the same interface, but isn't typehinted either ($options missing iterable type)
How can I test that?
> Add FormTypeExtensionInterface stub

- extension.neon
- stubs/Node.stub
- stubs/ParameterBag.stub
Repeat of #80 with already existing stubs removed.
These solve errors like:
```
Method AppBundle\Templating\Twig\TokenParser\MyNode::
parse() return type has no value type specified in iterable type Twig\Node\Node.
💡 Consider adding something like Twig\Node\Node<Foo> to the PHPDoc.
```
or
```
Method AppBundle\Controller\Test::validateRequestData()
has parameter $data with no value type specified in iterable type Symfony\Component\HttpFoundation\ParameterBag.
💡 Consider adding something like Symfony\Component\HttpFoundation\ParameterBag<Foo> to the PHPDoc.
```
> Add stubs for Twig Node and Symfony ParameterBag

- README.md
This updates the readme to add the solution given in https://github.com/phpstan/phpstan/issues/4272#event-4175079095
I also advised to create a new env for performance reasons.
> Update readme for console analysis

- composer.json
- extension.neon
- src/Type/Symfony/TreeBuilderDynamicReturnTypeExtension.php
- src/Type/Symfony/TreeBuilderGetRootNodeDynamicReturnTypeExtension.php
- src/Type/Symfony/TreeBuilderType.php
- tests/Type/Symfony/EnvelopeReturnTypeExtensionTest.php
- tests/Type/Symfony/ExtensionTestCase.php
- tests/Type/Symfony/HeaderBagDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/InputBagDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/InputInterfaceGetArgumentDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/InputInterfaceGetOptionDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/KernelInterfaceDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/RequestDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/SerializerDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/ServiceDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/TreeBuilderDynamicReturnTypeExtensionTest.php
- tests/Type/Symfony/tree_builder.php
After seeing #60 stuck I decided to give it a shot... 
This is very naive, and it assumes the `TreeBuilder` is always of type `array`.
```
TreeBuilder::__construct(string $name, string $type = 'array', NodeBuilder $builder = null)
```
If I am able to find the second `$type` parameter to the `new TreeBuilder()` call then I can make the return type of `getRootNode` dynamic based on that.
@ondrejmirtes Is this even possible?
The issue with NodeDefinition::end() is that it can return `null` when you've reached the root. The current extension removes the nullability in favor of DX. But it's also very naive. No idea if that can be done dynamically.
Hope to get some advice on how to proceed.... 🙏
> Support for TreeBuilder::getRootNode()

- extension.neon
- tests/Type/Symfony/Config/TreeBuilderTest.php
Related to https://github.com/phpstan/phpstan-symfony/pull/131 cc @ruudk 
BeforeNormalization has the same behavior than validate.
This fix an issue with 
```
->children()
->arrayNode('information')
->useAttributeAsKey('id')
->prototype('array')
->beforeNormalization()
->ifString()
->then(static function ($v) {
return [$v];
})
->end()
->prototype('scalar')->end()
->end(
```
```
Call to an undefined method Symfony\Component\Config\Definition\Builder\NodeDefinition::prototype().
```
I tried it on my project and it fix the error. A release after the merge could be great if you have time @ondrejmirtes :)
> Fix beforeNormalization

- stubs/ContextAwareDenormalizerInterface.stub
- stubs/ContextAwareNormalizerInterface.stub
- stubs/DenormalizerInterface.stub
- stubs/EncoderInterface.stub
- stubs/NormalizerInterface.stub
> Fix serializer stubs

- README.md
* The code is taken from https://github.com/phpstan/phpstan-symfony/issues/141#issuecomment-817485623
* In the introduction I emphasized more that this is only relevant if you have Console Commands (right?)
Closes https://github.com/phpstan/phpstan-symfony/issues/141
> Adding console-application.php for Symfony 5

- src/Rules/Symfony/ContainerInterfacePrivateServiceRule.php
- tests/Rules/Symfony/ExampleController.php
- tests/Rules/Symfony/container.xml
Now when private services are fetching from Psr\Container\ContainerInterface::get(), an error "Service "%s" is private" occurred.
But Symfony has [ServiceLocators](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-locator) in order to define smaller containers with public access to services.
This PR solves error "Service "%s" is private" when service is fetching from ServiceLocator.
> Support for ServiceLocator

- src/Type/Symfony/ServiceDynamicReturnTypeExtension.php
- tests/Type/Symfony/container.xml
- tests/Type/Symfony/data/ExampleAbstractController.php
- tests/Type/Symfony/data/ExampleAbstractControllerWithoutContainer.php
- tests/Type/Symfony/data/ExampleController.php
- tests/Type/Symfony/data/ExampleControllerWithoutContainer.php
When a synthetic service has a class. We should use that for the type.
All tests are red on my Machine, so I didn't write a test 😓 
Issue: #154
> Fix synthetic return type when class is available

- .github/workflows/build.yml
- composer.json
Related to https://github.com/phpstan/phpstan-mockery/pull/30#issuecomment-841182105
---
> chore: Use the latest PHPUnit wherever possible

- stubs/Symfony/Component/Serializer/Normalizer/DenormalizableInterface.stub
See https://github.com/symfony/symfony/pull/39561
DenormalizableInterface::denormalize() should not return anything, so the `@return` declaration should be removed. If you look at the usage in `CustomNormalizer::denormalize()`, it becomes clear that this method shouldn't return anything:
```php
public function denormalize($data, $type, $format = null, array $context = [])
{
$object = $this->extractObjectToPopulate($type, $context) ?: new $type();
$object->denormalize($this->serializer, $data, $format, $context);
return $object;
}
```
Note that in this case `$object implements DenormalizableInterface`, so this is about the `$object->normalize()` call above.
> Fix DenormalizableInterface::denormalize() return type declaration

- extension.neon
- stubs/Symfony/Component/EventDispatcher/EventDispatcherInterface.stub
As the event dispatcher returns the event it gets as parameter, it makes sense to introduce a stub with a template for that
> Introduce stub for EventDispatcherInterface

- extension.neon
- stubs/Symfony/Component/Security/Acl/Model/AclInterface.stub
- stubs/Symfony/Component/Security/Acl/Model/EntryInterface.stub
HI @ondrejmirtes, the security stubs were fixing two things:
- The `AclProviderInterface`/`MutableAclProviderInterface` issue. This will be fixed in Symfony 5.4 and wasn't easily fixed in phpstan.
- The array keys of the `AclInterface` methods wich is int (and not string|int). I opened a PR on Symfony, but having the stub here allow to fix the issue for all the version of symfony (even < 5.4). For instance the sonata build is currently failing because of the removal of this stub.
So I think we should add it back.
> Add back AclInterface stub

- src/Rules/Symfony/ContainerInterfaceUnknownServiceRule.php
- tests/Rules/Symfony/ContainerInterfaceUnknownServiceRuleTest.php
- tests/Rules/Symfony/ExampleServiceSubscriber.php
Fixes #191
I also added a test (not sure if it's correct)
> Ignore ContainerBagInterface in ContainerInterfaceUnknownServiceRule

- stubs/Symfony/Component/Validator/Constraint.stub
Getting this error on a custom constraint. Adding the type in the stub fixes it.
```
Library/Symfony/Constraint/BankAccount.php:26
↳ Type array<string, string> of property App\Library\Symfony\Constraint\BankAccount::$errorNames is not the same as type mixed of overridden property Symfony\Component\Validator\Constraint::$errorNames.
```
> Add Constraint::$errorNames

- extension.neon
- stubs/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.stub
- stubs/Symfony/Bundle/FrameworkBundle/Test/TestContainer.stub
This fixes the false positive reported in #27.
This makes sure that when you call `self::$container->get(...)` in a `KernelTestCase`, you don't get the 'Service ... is private.' error.
> Fix false positive "Service ... is private." when using KernelTestCase::$container

- src/Symfony/XmlServiceMapFactory.php
- tests/Symfony/DefaultServiceMapTest.php
- tests/Symfony/container.xml
- tests/Type/Symfony/container.xml
This fixes #75.
This changes marks services as private when they are not explicitly public.
> Services are private by default

- stubs/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.stub
> Followup of Symfony TestContainer issue

- src/Rules/Symfony/ContainerInterfacePrivateServiceRule.php
- tests/Rules/Symfony/ExampleServiceSubscriber.php
> Fix false positive about private service in service subscriber

- composer.json
- extension.neon
- src/Type/Symfony/Form/FormInterfaceDynamicReturnTypeExtension.php
- tests/Type/Symfony/ExtensionTest.php
- tests/Type/Symfony/data/FormInterface_getErrors.php
Hey there :wave: 
this is my attempt to fix https://github.com/phpstan/phpstan-symfony/issues/166
Hope I get everything right :see_no_evil: 
It took some time, but once I got how the test suite works, it was quite straight forward :+1: good job here!
Let me know, if something is missing :slightly_smiling_face:
> Introduce DynamicReturnTypeExtension for 'Symfony\Component\Form\FormInterface::getErrors'

- stubs/Symfony/Component/Form/FormView.stub
Hi @ondrejmirtes, since https://github.com/symfony/symfony/pull/44764/files the FormView phpstan-stub is wrong.
This create an issue because when using both phpstan and psalm, the first one require string as key when the second use the symfony definition and allow both int and string.
> Fix FormView stub

- stubs/Symfony/Contracts/Cache/CacheInterface.stub
The stub is missing the second save parameter on the callable that is defined in the [CallbackInterface](https://github.com/phpstan/phpstan-symfony/blob/96ee630098c49c1c25326ae51b027e469bfd2064/stubs/Symfony/Contracts/Cache/CallbackInterface.stub)
> Add missing save parameter to CacheInterface stub

- extension.neon
- src/Type/Symfony/ResponseHeaderBagDynamicReturnTypeExtension.php
- tests/Type/Symfony/ExtensionTest.php
- tests/Type/Symfony/data/response_header_bag_get_cookies.php
An attempt to make `ResponseHeaderBag::getCookies()` return dynamic type based on:
https://github.com/symfony/symfony/blob/c112bf116f8d4eb2d44a70dffaed8d7f4f10e521/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L225
which when `array` is passed, returns `$this->cookies` which contains:
https://github.com/symfony/symfony/blob/c112bf116f8d4eb2d44a70dffaed8d7f4f10e521/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php#L184
> Add dynamic return type to ResponseHeaderBag::getCookies

- composer.json
- src/Type/Symfony/ServiceDynamicReturnTypeExtension.php
- tests/Type/Symfony/container.xml
- tests/Type/Symfony/data/ExampleAbstractController.php
- tests/Type/Symfony/data/ExampleController.php
Fixes #226
~~It's simplest and optimistic implementation which does not support:~~
- ~~`%env()%` syntax~~
- ~~`%app.class%_decorator` mixed interpolation~~
Let me know if we can start with this or should we work on most advanced scenarios 🙂
> Support for parameterised service class
